displayName=Llama Club CC
author=HypeHypest
description=Sync player data and send clan event notifications to llamaclub.co.uk
tags=clan,datasyncs,llamaclub,events,webhooks
plugins=com.llamaclub.LlamaClubPlugin
version=1.0.1
build=standard